Add ver-1gc case
idaholab/TMAP8 pull request #107
Opened 2024-03-08 06:21 UTC by singhgp4321

Ref: #104

2024-03-08 06:30 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2106347/) on 3789321 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/tmap8/docs/PRs/107/site)

This comment will be updated on new commits.

2024-03-08 06:33 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2106346/) on 3789321 wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/tmap8/docs/PRs/107/coverage)



This comment will be updated on new commits.

2024-03-08 06:56 UTC, simopier commented
Thanks @singhgp4321!

2024-03-14 15:33 UTC, simopier requested changes
Thanks @singhgp4321 for the contribution. 

This is a great first step for this verification case. For anyone picking this up later: the next steps to complete this verification case before this can be merged are:

- [ ] Clean up input file
- [ ] Provide python script to automatically compare predictions to analytical equation and generate plots
- [ ] Create `test` file that runs the input file for testing and verification
- [ ] Create gold folder that contains test results and verification predictions
- [ ] Create documentation to present the case, discuss comparison against analytical solution and the quality of the verification, as well as potential differences with TMAP7 predictions.

2024-04-17 19:53 UTC, cticenhour commented
#126 has been merged, so this PR can be closed.

2024-04-17 19:53 UTC, closed without merging