Consoliate bibliography files and create initial publications page
idaholab/TMAP8 pull request #128
Opened 2024-04-15 15:53 UTC by cticenhour

Closes #127

Requesting review from @simopier

2024-04-15 16:07 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2175949/) on 8f8b5bc wanted to post the following:

View the site [here](https://mooseframework.inl.gov/tmap8/docs/PRs/128/site)

This comment will be updated on new commits.

2024-04-15 16:08 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2175948/) on 8f8b5bc wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/tmap8/docs/PRs/128/coverage)



This comment will be updated on new commits.

2024-04-15 16:35 UTC, cticenhour commented on doc/content/publications.md
> +!! ## Theses and Dissertations)
```suggestion
!! ## Theses and Dissertations
```

Need to remove this after review.

2024-04-17 14:35 UTC, moosebuild commented
Job [Test Debug](https://civet.inl.gov/job/2179465/) on 661e111 : invalidated by @simopier

The failure seems unrelated to this PR.

2024-04-17 17:38 UTC, simopier requested changes
Thank you @cticenhour, I just have a small comment.

2024-04-17 17:38 UTC, simopier commented on doc/content/verification_and_validation/index.md
> +TMAP8 also contains [example cases](examples/index.md), which showcase how TMAP8 can be used. Finally, for more references of TMAP8 usage, a list of publications that use TMAP8 can be found [here](pu
```suggestion
TMAP8 also contains [example cases](examples/index.md), which showcase how TMAP8 can be used. Finally, for more references of TMAP8 usage, a list of publications supporting TMAP8 development can be found [here](publications.md).
```

2024-04-17 17:38 UTC, simopier commented on doc/content/publications.md
> +Below is a known list of publications using TMAP8, and might be incomplete. If
```suggestion
Below is a known list of publications supporting TMAP8 development, and might be incomplete. If
```

2024-04-17 21:08 UTC, cticenhour commented
@simopier I accept your suggestions - ready for another look!

2024-04-17 22:02 UTC, simopier approved these changes
Thank you, @cticenhour!!

2024-04-17 22:02 UTC, merged