Capability improvements to enable TDS
idaholab/TMAP8 pull request #135
Opened 2024-05-17 00:34 UTC by simopier

This PR improves current TMAP8 to support thermal desorption spectroscopy (TDS) modeling. 

The commit messages describe what is being done. 

(Ref. #133) - a follow up PR will add an example case for TDS to complete this issue, but this PR already grew large enough.. 
(Close. #134)

2024-05-17 00:40 UTC, simopier commented
I created #136 to potentially add deprecated tests in CIVET recipes since it would be nice to run them here.

2024-05-17 00:48 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2236742/) on 62960f4 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/tmap8/docs/PRs/135/site)

This comment will be updated on new commits.

2024-05-17 00:59 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2236741/) on 62960f4 wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>9496e1</th>
      <th colspan=4>#135 62960f</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>91.04%</td>
      <td>91.29%</td>
      <td>+0.25%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>315</td>
      <td>325</td>
      <td>+10</td>
      <td>34</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>31</td>
      <td>31</td>
      <td>-</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/tmap8/docs/PRs/135/coverage_diff)

[Full coverage report](https://mooseframework.inl.gov/tmap8/docs/PRs/135/coverage)



This comment will be updated on new commits.

2024-05-23 01:28 UTC, cticenhour commented
@simopier should have time to give this a full review tomorrow.

2024-05-24 15:10 UTC, cticenhour requested changes

2024-05-24 15:10 UTC, cticenhour commented on src/nodal_kernels/TrappingNodalKernel.C
> +      "mobile", "The variable representing the mobile concentration of solute particles (1/m^3)");
I think this is a bit too vague. `mobile_concentration` instead?

2024-05-24 15:10 UTC, cticenhour commented on test/tests/bcs/EquilibriumBC/equilibriumBC.i
> +[]
This seems to be a simple test. Can this executioner block be simplified? I would guess so.

2024-05-24 15:10 UTC, cticenhour commented on test/tests/bcs/EquilibriumBC/tests
> +  [equilibriumBC_fiel_variable]
```suggestion
  [equilibriumBC_field_variable]
```

2024-05-26 00:55 UTC, simopier commented on test/tests/bcs/EquilibriumBC/tests
> +  [equilibriumBC_fiel_variable]
Great catch!

2024-05-28 19:03 UTC, cticenhour requested changes
A couple more items that were missed / reconsidered. I think this is ready to go after these are addressed.

2024-05-28 19:03 UTC, cticenhour commented on test/tests/bcs/EquilibriumBC/tests
> +    requirement = 'The system shall compute the flux imposed by EquilibriumBC when a field variable is used for the enclosure variable.'
```suggestion
    requirement = 'The system shall compute the equilibrium flux condition between an enclosure and a structure when a field variable is used for the enclosure variable.'
```

On second thought, let's not use the object name. The object and its usage should _ideally_ arise from the requirement, not the other way around.

2024-05-28 19:59 UTC, cticenhour approved these changes

2024-05-28 19:59 UTC, merged