Interface sorption 202407
idaholab/TMAP8 pull request #157
Opened 2024-07-25 22:18 UTC by simopier

Update `InterfaceSorptionSievert` into `InterfaceSorption` to make it general:
- The exponent in the sorption law can now be user-defined
- Update documentation
- Edit existing tests and add tests for Henry's law
- Update name of test folder to reflect generalization

(close. #156)

2024-07-25 22:31 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2351784/) on bb44030 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/tmap8/docs/PRs/157/site)

This comment will be updated on new commits.

2024-07-25 22:34 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2351783/) on bb44030 wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>895c4f</th>
      <th colspan=4>#157 bb4403</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>91.32%</td>
      <td>91.39%</td>
      <td>+0.07%</td>
      <td>94.19%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>326</td>
      <td>329</td>
      <td>+3</td>
      <td>81</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>31</td>
      <td>31</td>
      <td>-</td>
      <td>5</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/tmap8/docs/PRs/157/coverage_diff)

[Full coverage report](https://mooseframework.inl.gov/tmap8/docs/PRs/157/coverage)



This comment will be updated on new commits.

2024-07-29 20:57 UTC, cticenhour requested changes

2024-07-29 20:57 UTC, cticenhour commented on doc/content/source/interfacekernels/InterfaceSorption.md
> +where $R$ is the ideal gas constant in J/mol/K, $T$ is the temperature in K, and $K$ is the solubility, and $n$ is the exponent of the sorption law. $K$ which is described as an Arrhenius equation:
```suggestion
where $R$ is the ideal gas constant in J/mol/K, $T$ is the temperature in K, $K$ is the solubility, and $n$ is the exponent of the sorption law. $K$ is described as an Arrhenius equation:
```

2024-07-29 20:57 UTC, cticenhour commented on doc/content/source/interfacekernels/InterfaceSorption.md
> +- $n=1/2$ corresponds to Sievert's law.
```suggestion
- $n = 1/2$ corresponds to Sievert's law.
```

2024-07-29 20:57 UTC, cticenhour commented on doc/content/source/interfacekernels/InterfaceSorption.md
> +When using the default, non-penalty method to enforcing flux conditions at the interface, a kernel such as [MatDiffusion](/MatDiffusion.md) must be applied to the neighbor block to form the correct r
```suggestion
When using the default, non-penalty method to enforce flux conditions at the interface, a kernel such as [MatDiffusion](/MatDiffusion.md) must be applied to the neighbor block to form the correct residual.
```

2024-07-29 20:57 UTC, cticenhour commented on test/tests/interfacekernels/InterfaceSorption/tests
> +  issues = '#50 #0000000'
```suggestion
  issues = '#50'
```

2024-07-29 20:57 UTC, cticenhour commented on test/tests/interfacekernels/InterfaceSorption/tests
> +    requirement = 'The system shall have the capability to enforce interfacial conditions based on the Sievert law in isothermal conditions using penalty-enforced flux balance.'
```suggestion
    requirement = 'The system shall have the capability to enforce interfacial conditions based on the Sievert law in isothermal conditions using a penalty-enforced flux balance.'
```

2024-07-29 20:57 UTC, cticenhour commented on test/tests/interfacekernels/InterfaceSorption/tests
> +    requirement = 'The system shall have the capability to enforce interfacial conditions based on the Sievert law in isothermal conditions using automatic differentiation and penalty-enforced flux b
```suggestion
    requirement = 'The system shall have the capability to enforce interfacial conditions based on the Sievert law in isothermal conditions using automatic differentiation and a penalty-enforced flux balance.'
```

2024-07-29 20:57 UTC, cticenhour commented on test/tests/interfacekernels/InterfaceSorption/tests
> +    requirement = 'The system shall have the capability to enforce interfacial conditions based on the Henry law in isothermal conditions using penalty-enforced flux balance.'
```suggestion
    requirement = 'The system shall have the capability to enforce interfacial conditions based on the Henry law in isothermal conditions using a penalty-enforced flux balance.'
```

2024-07-29 20:57 UTC, cticenhour commented on test/tests/interfacekernels/InterfaceSorption/tests
> +    requirement = 'The system shall have the capability to enforce interfacial conditions based on the Henry law in isothermal conditions using automatic differentiation and penalty-enforced flux bal
```suggestion
    requirement = 'The system shall have the capability to enforce interfacial conditions based on the Henry law in isothermal conditions using automatic differentiation and a penalty-enforced flux balance.'
```

2024-07-30 04:26 UTC, simopier commented on include/interfacekernels/InterfaceSorption.h
> +  /// Exponent of the Sorption law
```suggestion
  /// Exponent of the sorption law
```

2024-07-30 04:27 UTC, simopier commented on include/interfacekernels/InterfaceSorption.h
> +  /// Exponent of the Sorption law
Made it not capitalized since it's a noun. Good catch!

2024-07-31 15:31 UTC, cticenhour approved these changes

2024-07-31 15:31 UTC, merged