Add input section for V&V documentation
idaholab/TMAP8 pull request #172
Opened 2024-09-11 22:59 UTC by lin-yang-ly

Add the input section for all V&V documentation

(refs #150)

## Reason

## Design

## Impact

2024-09-11 23:03 UTC, lin-yang-ly commented
@chaibhave It is ready for review. Thank you!

2024-09-11 23:48 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2440257/) on 3b9776c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/tmap8/docs/PRs/172/site)

This comment will be updated on new commits.

2024-09-11 23:52 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2440256/) on 3b9776c wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/tmap8/docs/PRs/172/coverage)



This comment will be updated on new commits.

2024-09-14 06:15 UTC, simopier requested changes
Thank you!

2024-09-14 06:15 UTC, simopier commented on doc/content/verification_and_validation/ver-1b.md
> +The input file for this case can be found at [/ver-1b.i] which is different from the input file used as test in TMAP8. To limit the computational costs of the test cases, the tests run a version of t
```suggestion
The input file for this case can be found at [/ver-1b.i], which is different from the input file used as test in TMAP8. To limit the computational costs of the test cases, the tests run a version of the file with a coarser mesh and larger time steps. More information about the changes can be found in the test specification file for this case [/ver-1b/tests].
```

2024-09-14 06:15 UTC, simopier commented on doc/content/verification_and_validation/ver-1d.md
> +The input files for the cases where diffusion and trapping are the rate limiting processes can be found at [/ver-1d-diffusion.i] and [/ver-1d-trapping.i]. These input files are different from the inp
```suggestion
The input files for the cases where diffusion and trapping are the rate limiting processes can be found at [/ver-1d-diffusion.i] and [/ver-1d-trapping.i], respectively. These input files are different from the input files used as tests in TMAP8. To limit the computational costs of the test cases, the tests run a version of the files with a coarser mesh and fewer time steps. More information about the changes can be found in the test specification file for this case, namely [/ver-1d/tests].
```

2024-09-14 06:15 UTC, simopier commented on doc/content/verification_and_validation/ver-1g.md
> +The input file for these cases can be found at [/ver-1g.i], which is also used as test in TMAP8 at [/ver-1g/tests]. The initial conditions of three cases (a), (b), and (c) can be found at [/equal_con
```suggestion
The input file for these cases can be found at [/ver-1g.i], which is also used as tests in TMAP8 at [/ver-1g/tests]. The initial conditions of three cases (a), (b), and (c) can be found at [/equal_conc.i], [/diff_conc_TMAP4.i], and [/diff_conc_TMAP7.i], respectively.
```

2024-09-18 14:51 UTC, simopier approved these changes
Thank you @lin-yang-ly!

2024-09-18 14:52 UTC, merged

2024-09-24 18:01 UTC, simopier commented
(ref. #167)