Add verification case 1dd
idaholab/TMAP8 pull request #175
Opened 2024-09-17 21:43 UTC by lin-yang-ly

- add ver-1dd folder
- add corresponding documentation

(Ref. #169)

2024-09-17 21:57 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2452214/) on cf9ce87 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/tmap8/docs/PRs/175/site)

This comment will be updated on new commits.

2024-09-18 15:51 UTC, simopier requested changes
Some preliminary comments.

2024-09-18 15:51 UTC, simopier commented on doc/content/verification_and_validation/ver-1dd.md
> +The input file for this case can be found at [/ver-1dd.i] which is also used as test in TMAP8 at [/ver-1dd/tests].
```suggestion
The input file for this case can be found at [/ver-1dd.i], which is also used as test in TMAP8 at [/ver-1dd/tests].
```

2024-09-18 15:51 UTC, simopier commented on test/tests/ver-1dd/comparison_ver-1dd.py
> +ax.set_xlim(left=0)
```suggestion
ax.set_xlim(left=0, right=1.5)
```
Otherwise everything is on the left of the graph.

2024-09-18 15:51 UTC, simopier commented on test/tests/ver-1dd/comparison_ver-1dd.py
> +# Calculate the breakthrough time from numberical solution
```suggestion
# Calculate the breakthrough time from numerical solution
```

2024-09-18 15:51 UTC, simopier commented on test/tests/ver-1dd/comparison_ver-1dd.py
> +# Calculate the breakthrough time from numberical solution
If this is an error due to copy pasting, please correct the original .py file as well

2024-09-18 15:51 UTC, simopier commented on test/tests/ver-1dd/tests
> +    heavy = true
```suggestion
```
I don't think we need `heavy` here.

2024-09-18 17:12 UTC, simopier commented on test/tests/ver-1dd/gold/ver-1dd_out.csv
How was this changes in the latest commits?

2024-09-18 17:13 UTC, simopier reviewed
What did you change in the input file to warrant regolding? 

EDIT: it was a change in the number of `nl_rel_tol`.

2024-09-18 17:16 UTC, lin-yang-ly commented on test/tests/ver-1dd/gold/ver-1dd_out.csv
I added nl_abs_tol in Executioner at input file to avoid the mult-processors issue on checks. So I updated the output files in gold to ensure the consistency. Is that the reason the pre-check is canceled?

2024-09-18 21:46 UTC, simopier commented
the Apptainer openmpi error reads:
```
ver-1dd.ver-1d_comparison: Working Directory: /tmp/tmap8test.p5n9NG/tests/tmap8/tests/tests/ver-1dd
ver-1dd.ver-1d_comparison: Running command: python3 comparison_ver-1dd.py
ver-1dd.ver-1d_comparison: Traceback (most recent call last):
ver-1dd.ver-1d_comparison:   File "/tmp/tmap8test.p5n9NG/tests/tmap8/tests/tests/ver-1dd/comparison_ver-1dd.py", line 18, in <module>
ver-1dd.ver-1d_comparison:     tmap_sol = pd.read_csv(os.path.join(git.Repo('.',search_parent_directories=True).working_tree_dir, "test/tests/ver-1dd/gold/ver-1dd_out.csv"))
ver-1dd.ver-1d_comparison:   File "/opt/miniforge3/envs/moose/lib/python3.10/site-packages/git/repo/base.py", line 289, in __init__
ver-1dd.ver-1d_comparison:     raise InvalidGitRepositoryError(epath)
ver-1dd.ver-1d_comparison: git.exc.InvalidGitRepositoryError: /tmp/tmap8test.p5n9NG/tests/tmap8/tests/tests/ver-1dd
ver-1dd.ver-1d_comparison: 
ver-1dd.ver-1d_comparison: ################################################################################
ver-1dd.ver-1d_comparison: Tester failed, reason: CODE 1
ver-1dd.ver-1d_comparison: 
[1.306s]     FAIL ver-1dd.ver-1d_comparison FAILED (CODE 1)
```

2024-09-18 21:52 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2453716/) on 7a96ef9 wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/tmap8/docs/PRs/175/coverage)



This comment will be updated on new commits.

2024-09-18 23:04 UTC, lin-yang-ly commented
> the Apptainer openmpi error reads:
> 
> ```
> ver-1dd.ver-1d_comparison: Working Directory: /tmp/tmap8test.p5n9NG/tests/tmap8/tests/tests/ver-1dd
> ver-1dd.ver-1d_comparison: Running command: python3 comparison_ver-1dd.py
> ver-1dd.ver-1d_comparison: Traceback (most recent call last):
> ver-1dd.ver-1d_comparison:   File "/tmp/tmap8test.p5n9NG/tests/tmap8/tests/tests/ver-1dd/comparison_ver-1dd.py", line 18, in <module>
> ver-1dd.ver-1d_comparison:     tmap_sol = pd.read_csv(os.path.join(git.Repo('.',search_parent_directories=True).working_tree_dir, "test/tests/ver-1dd/gold/ver-1dd_out.csv"))
> ver-1dd.ver-1d_comparison:   File "/opt/miniforge3/envs/moose/lib/python3.10/site-packages/git/repo/base.py", line 289, in __init__
> ver-1dd.ver-1d_comparison:     raise InvalidGitRepositoryError(epath)
> ver-1dd.ver-1d_comparison: git.exc.InvalidGitRepositoryError: /tmp/tmap8test.p5n9NG/tests/tmap8/tests/tests/ver-1dd
> ver-1dd.ver-1d_comparison: 
> ver-1dd.ver-1d_comparison: ################################################################################
> ver-1dd.ver-1d_comparison: Tester failed, reason: CODE 1
> ver-1dd.ver-1d_comparison: 
> [1.306s]     FAIL ver-1dd.ver-1d_comparison FAILED (CODE 1)
> ```

I believe the error is from the running python script in Apptainer test environment. Once I remove the `heavy=true` in test file and activate the test in Apptainer. The error will happen. The same issue will happen if I remove the `heavy=true` in other  cases in PR #174. The possible reason is the git package in Apptainer test environment cannot read the correct work path and need to be updated.

2024-09-27 04:23 UTC, simopier requested changes
Just a few minor changes, and it's good to go!
Thank you!

2024-09-27 04:23 UTC, simopier commented on test/tests/ver-1dd/tests
> +    prereq = 'ver-1dd'
```suggestion
```

2024-09-27 04:23 UTC, simopier commented on doc/content/verification_and_validation/ver-1dd.md
> +This problem models permeation through a membrane with a constant source in which no trap presented. We solve the following equations
```suggestion
This problem models permeation through a membrane with a constant source in which no trap presented. We solve 
```

2024-09-27 04:23 UTC, simopier commented on doc/content/verification_and_validation/ver-1dd.md
> +where $C_M$ is the concentrations of the mobile, $D$ is the diffusivity of the mobile species.
```suggestion
where $C_M$ is the concentrations of the mobile, $D$ is the diffusivity of the mobile species, and $t$ is the time.
```

2024-09-27 04:23 UTC, simopier commented on doc/content/verification_and_validation/ver-1dd.md
> +## Test Description
The test description should list the values of the model parameters and case configurations, like the thickness of the plate, the diffusivity, etc. 
It is OK to say: 
`we use the same values as in [link to ver-1d],`
 but you need to make sure there is no confusion for the user.

2024-09-27 04:23 UTC, simopier commented on doc/content/verification_and_validation/ver-1dd.md
> +This verification problem is taken from [!cite](ambrosek2008verification) and builds on the capabilities verified in [ver-1d](ver-1d.md) and [ver-1dc](ver-1dc.md). However, in the current case, there
```suggestion
This verification problem is taken from [!cite](ambrosek2008verification) and builds on the capabilities verified in [ver-1d](ver-1d.md) and [ver-1dc](ver-1dc.md). The configuration and modeling parameters are the same as in [ver-1d](ver-1d.md), except that, in the current case, there are no traps in the membrane. This case is simulated in [/ver-1dd.i].
```
The test description should list the values of the model parameters and case configurations, like the thickness of the plate, the diffusivity, etc. 
It is OK to say: 
`we use the same values as in [link to ver-1d],`
 but you need to make sure there is no confusion for the user.

2024-09-27 04:23 UTC, simopier commented on doc/content/verification_and_validation/ver-1dd.md
> +The analytical solution for the permeation transient is compared with TMAP8 results in [ver-1dd_comparison_diffusion]. The graphs for the theoretical flux and the calculated flux are in good agreemen
```suggestion
The analytical solution for the permeation transient is compared with TMAP8 results in [ver-1dd_comparison_diffusion]. The graphs for the theoretical flux and the calculated flux are in good agreement, with root mean square percentage errors (RMSPE) of RMSPE = 0.14 % for $t \geq 0.01$ s. The breakthrough time calculated from the analytical solution provided by [eqn:tau_be] is 0.05 s, and the breakthrough time from TMAP8 is 0.05 s, so it matches.
```

2024-09-27 14:49 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2471564/), step Sync to remote on 21ad273 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/tmap8/docs/PRs/175/site)

This comment will be updated on new commits.

2024-09-27 14:49 UTC, lin-yang-ly commented
> Just a few minor changes, and it's good to go! Thank you!

No confusion in current documentation with the updates. Thank you PC! The PR is ready to move forward.

2024-09-27 15:41 UTC, simopier approved these changes
Thank you for adding this new case!

2024-09-27 15:41 UTC, merged