Add TMAP8 getting started documentation and clean-up homepage
idaholab/TMAP8 pull request #20
Opened 2022-07-26 19:50 UTC by cticenhour

@singhgp4321 @lindsayad here are the new getting started documentation pages I was thinking of when meeting with the INL Fusion Safety team. I also cleaned up the homepage and moved Alex's Scaling notes to a "User Notes" page - perhaps we can keep this page updated with good usage guidelines in the future? 

Closes #19

2022-07-26 20:23 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1119436/) on cd54b29 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/TMAP8/docs/PRs/20/site)

This comment will be updated on new commits.

2022-07-26 21:26 UTC, lindsayad requested changes
looks great overall!

2022-07-26 21:26 UTC, lindsayad commented on doc/content/getting_started/installation.md
> +conda activate moose
```suggestion
mamba activate moose
```

2022-07-26 21:42 UTC, cticenhour commented on doc/content/getting_started/installation.md
> +conda activate moose
Oops good call! 😄

2022-07-26 21:43 UTC, lindsayad approved these changes

2022-07-29 00:45 UTC, merged

2022-07-30 21:29 UTC, singhgp4321 commented
Thanks for adding this @cticenhour !