Minor Correction on Validation Cases
idaholab/TMAP8 pull request #219
Opened 2024-11-14 00:25 UTC by yfche

## Reason

## Design

## Impact

2024-11-14 04:32 UTC, simopier requested changes
Just some minor comments, thank you for this fix!

2024-11-14 04:32 UTC, simopier commented on test/tests/val-2c/comparison_val-2c.py
> +tmap8_time_delay = tmap8_prediction_delay['time']
Good catch!

2024-11-14 04:32 UTC, simopier commented on test/tests/val-2b/gold/experimental_data.csv
> +740.2129636,-0.020131166
```suggestion
740.2129636,0
```
The values should be positive, this is an artifact of the plot digitization.

2024-11-14 04:39 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2548916/), step Sync to remote on e6b2d70 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/tmap8/docs/PRs/219/site)

This comment will be updated on new commits.

2024-11-14 04:48 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2548915/), step Generate coverage on e6b2d70 wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/tmap8/docs/PRs/219/coverage)



This comment will be updated on new commits.

2024-11-14 21:26 UTC, yfche commented
@simopier Is there a way to get around the "Test Heavy" error? I ran into it with the previous push, too.
Also, just being curious, is there a reason why the checks are taking so long today?

2024-11-14 22:57 UTC, simopier commented
The heavy tests were recently added, and the failures are unrelated to this change. I have a fix about to be pushed. 

I think it's because I first needed to activate the tests, and then it might have been slow because of the HPC outage.

2024-11-15 00:07 UTC, simopier approved these changes
Thank you!

2024-11-21 20:06 UTC, merged