Adding val-1fa and val-1fb verification cases
idaholab/TMAP8 pull request #22
Opened 2022-08-01 17:16 UTC by singhgp4321

Ref: #12

2022-08-01 22:32 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1125491/) on 86a849c wanted to post the following:

View the site [here](https://mooseframework.inl.gov/TMAP8/docs/PRs/22/site)

This comment will be updated on new commits.

2022-08-02 19:50 UTC, singhgp4321 commented
@cticenhour It's still failing the documentation test although I made those updates in the yml file.

2022-08-02 19:55 UTC, cticenhour commented
I will take a closer look! Thanks for the heads up.

2022-08-02 20:47 UTC, cticenhour requested changes
I can't make these suggestions in the general GitHub interface for some reason, but I would also make these changes: 
```
diff --git a/doc/config.yml b/doc/config.yml
index 4832f50..59fb4ac 100644
--- a/doc/config.yml
+++ b/doc/config.yml
@@ -16,7 +16,7 @@ Extensions:
             Documentation:
               TMAP8-only Syntax: syntax/tmap_only.md
               Complete Code Syntax: syntax/index.md
-            Software Quality: sqa/index.md
+            Software Quality: /sqa/index.md
     MooseDocs.extensions.appsyntax:
         executable: ${ROOT_DIR}
         includes:
diff --git a/doc/sqa_reports.yml b/doc/sqa_reports.yml
index cdcf159..bb89603 100644
--- a/doc/sqa_reports.yml
+++ b/doc/sqa_reports.yml
@@ -24,5 +24,6 @@ Requirements:
         working_dirs:
             - ${ROOT_DIR}/doc/content
             - ${MOOSE_DIR}/framework/doc/content
+            - ${MOOSE_DIR}/modules/heat_conduction/doc/content
         directories:
             - ${ROOT_DIR}/test
```

2022-08-02 20:47 UTC, cticenhour commented on doc/config.yml
> +    - ${MOOSE_DIR}/modules/heat_conduction/doc/content
```suggestion
    - ${MOOSE_DIR}/modules/heat_conduction/doc/content
    - ${MOOSE_DIR}/modules/ray_tracing/doc/content      # pulled in by heat_conduction
```

You'll need this for the main documentation build (heat conduction has ray tracing as a dependency). I would also explicitly list `RAY_TRACING := yes` in the Makefile for the reminder to the developers that this dependency exists.

2022-08-02 20:47 UTC, cticenhour commented on doc/config.yml
> +            heat_conduction: !include ${MOOSE_DIR}/modules/heat_conduction/doc/sqa_heat_conduction.yml
```suggestion
            heat_conduction: !include ${MOOSE_DIR}/modules/heat_conduction/doc/sqa_heat_conduction.yml
            ray_tracing: !include ${MOOSE_DIR}/modules/ray_tracing/doc/sqa_ray_tracing.yml
```

2022-08-02 20:49 UTC, cticenhour commented
All of these changes should fix both the SQA fail and the general documentation build fail.

2022-08-16 16:01 UTC, cticenhour approved these changes

2022-08-16 16:16 UTC, cticenhour commented
@singhgp4321 Just checking - are you still pulling the verification documentation text from the older TMAP manual? 

It seems that branch protection rules are preventing me from merging this right now, even though I have write access. Pinging @lindsayad about it, though it might be a bit before he is in a position to respond.

2022-08-16 16:48 UTC, merged

2022-08-19 17:11 UTC, singhgp4321 commented
@cticenhour For this MR I wrote the documentation text, although I try to use what is already in the V&V report.