TMAP8 clean up V&V cases
idaholab/TMAP8 pull request #227
Opened 2024-12-01 16:59 UTC by simopier

(Ref. #12)

2024-12-01 17:19 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2574797/), step Sync to remote on 586a0e5 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/tmap8/docs/PRs/227/site)

This comment will be updated on new commits.

2024-12-01 17:25 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2574796/), step Generate coverage on 586a0e5 wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/tmap8/docs/PRs/227/coverage)



This comment will be updated on new commits.

2024-12-02 17:00 UTC, cticenhour requested changes
I have a few items I believe need to be addressed.

2024-12-02 17:26 UTC, simopier commented on test/tests/ver-1dc/gold/ver-1dc_out.e
This is because two PRs conflicted.

I was originally fixing the failure of heavy tests in this PR, but ended up creating a different PR: https://github.com/idaholab/TMAP8/pull/224

I think this comes from some errors in resolving conflicts. The change are probably minimal, though. I'll try to remove it.

2024-12-02 17:44 UTC, simopier commented on doc/content/verification_and_validation/ver-1c.md
> +The value of $C$ found in [!cite](longhurst1992verification) has a typographical error, $\sqrt{Dt}$ should be at the denominator. [eq:c_func_4] follows the form of [!cite](Carslaw1959conduction).
removed

2024-12-02 17:44 UTC, simopier commented on doc/content/verification_and_validation/ver-1fb.md
> +At the initial time and steady state, the solution from TMAP7 matches the real thermal distribution, whereas the solution from TMAP4 does not. Thus, TMAP8 selects the solution from TMAP7 as the analy
Thank you! Done in upcoming push.

2024-12-02 17:54 UTC, simopier commented on test/tests/ver-1dc/gold/ver-1dc_out.e
removed.

2024-12-02 20:07 UTC, merged