Update the analytical solution for verification case ver-1e
idaholab/TMAP8 pull request #228
Opened 2024-12-02 15:16 UTC by lin-yang-ly

Update the analytical solution of SiC and PyC layers for ver-1e in documentation and python script.

(Ref. #123)

2024-12-02 15:35 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2576164/), step Generate coverage on 8f0fecf wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/tmap8/docs/PRs/228/coverage)



This comment will be updated on new commits.

2024-12-02 16:35 UTC, simopier commented on doc/content/verification_and_validation/ver-1e.md
> +       caption=Comparison of TMAP8 calculation with the analytical solution in SiC layer. Bold text next to the plot curves shows the RMSPE for the match between the TMAP8 prediction and analytical s
Please specify the position of the point in the caption.

2024-12-02 17:30 UTC, lin-yang-ly commented on doc/content/verification_and_validation/ver-1e.md
> +       caption=Comparison of TMAP8 calculation with the analytical solution in PyC layer. Bold text next to the plot curves shows the RMSPE for the match between the TMAP8 prediction and analytical s
Hello PC, I tried the deeper distance (x=32 nm, the interface is 33 nm) in PyC layer. However, the results reached the equilibrium immediately as well. The main reason is we have a very large diffusivity in PyC (D=1.274e-7), which is 10e4 times than diffusivity in SiC (2.622e-11). Also, the value is not accurate if I closeup to the time from 0 to 0.01 s for the comparison in PyC layer.

2024-12-02 19:05 UTC, simopier requested changes
Just minor changes. I'll need to doubele check the documentation, but otherwise things look great!
Thank you!

2024-12-02 19:05 UTC, simopier commented on doc/content/verification_and_validation/ver-1e.md
> +The error is calculated between the TMAP8 and analytical solution values after $t$ = 0.01 s. This is in order to ignore the unphysical predictions of the analytical solution at very small times as sh
```suggestion
The error is calculated between the TMAP8 and analytical solution values after $t$ = 0.01 s. This is in order to ignore the unphysical predictions of the analytical solution at very small times as shown in [ver-1e_comparison_time_zoomed], which is a close-up view of [ver-1e_comparison_time] close to the start of the simulation. The departure from physical results at low $t$ is due to the limited number of $\lambda_n$ values being used from [eqn:roots]. We use the $\lambda_n$ values from 0 to 100 in this case. The $\lambda_n$ values in larger range will only have limited improvement in the accuracy but increase the running time for the computation of the analytical solutions.
```

2024-12-02 19:05 UTC, simopier commented on doc/content/verification_and_validation/ver-1e.md
> +    $a$ = thickness of the PyC layer (33 $\mu$ m)
```suggestion
    $a$ = thickness of the PyC layer (33 $\mu$m)
```

2024-12-02 19:05 UTC, simopier commented on doc/content/verification_and_validation/ver-1e.md
> +    $l$ = thickness of the SiC layer (63 $\mu$ m in TMAP4 verification case, and 66 $\mu$ m in TMAP7 verification case)
```suggestion
    $l$ = thickness of the SiC layer (63 $\mu$m in TMAP4 verification case, and 66 $\mu$m in TMAP7 verification case)
```

2024-12-02 19:05 UTC, simopier commented on doc/content/verification_and_validation/ver-1e.md
> +[ver-1e_comparison_dist] shows the comparison of the TMAP8 calculation and the analytical solution for concentration after steady-state is reached. The plots show the TMAP8 and analytical solution co
```suggestion
[ver-1e_comparison_dist] shows the comparison of the TMAP8 calculation and the analytical solution for concentration after steady-state is reached. The plots show the TMAP8 and analytical solution comparisons for both the TMAP4 case ($l$ = 63 $\mu$m) and the TMAP7 case ($l$ = 66 $\mu$m).
```

2024-12-02 19:05 UTC, simopier commented on doc/content/verification_and_validation/ver-1e.md
> +For transient solution comparisons, we select two different points: One in the PyC layer at $x = 32$ $\mu$ m, and one in the SiC layer.
```suggestion
For transient solution comparisons, we select two different points: One in the PyC layer at $x = 32$ $\mu$m, and one in the SiC layer.
```

2024-12-02 19:05 UTC, simopier commented on doc/content/verification_and_validation/ver-1e.md
> +[ver-1e_comparison_time] shows the comparison of the TMAP8 calculation against the analytical solution in the SiC layer. In the TMAP4 case, $x$ = 41 $\mu$ m, and in the TMAP7 case, $x$ = 48.75 $\mu$
```suggestion
[ver-1e_comparison_time] shows the comparison of the TMAP8 calculation against the analytical solution in the SiC layer. In the TMAP4 case, $x$ = 41 $\mu$m, and in the TMAP7 case, $x$ = 48.75 $\mu$m.
```

2024-12-02 19:05 UTC, simopier commented on doc/content/verification_and_validation/ver-1e.md
> +       caption=Comparison of TMAP8 calculation with the analytical solution at $x = 32$ $\mu$ m in PyC layer. Bold text next to the plot curves shows the RMSPE for the match between the TMAP8 predict
```suggestion
       caption=Comparison of TMAP8 calculation with the analytical solution at $x = 32$ $\mu$m in PyC layer. Bold text next to the plot curves shows the RMSPE for the match between the TMAP8 prediction and analytical solution for the TMAP4 and TMAP7 verification cases.
```

2024-12-02 19:05 UTC, simopier commented on doc/content/verification_and_validation/ver-1e.md
> +       caption=Comparison of TMAP8 calculation with the analytical solution in SiC layer. The compared distances are $x$ = 41 $\mu$ m in the TMAP4 case and $x$ = 48.75 $\mu$ m in the TMAP7 case. Bold
```suggestion
       caption=Comparison of TMAP8 calculation with the analytical solution in SiC layer. The compared distances are $x$ = 41 $\mu$m in the TMAP4 case and $x$ = 48.75 $\mu$m in the TMAP7 case. Bold text next to the plot curves shows the RMSPE for the match between the TMAP8 prediction and analytical solution for the TMAP4 and TMAP7 verification cases.
```

2024-12-03 16:22 UTC, simopier reviewed
The conflicts need to be addressed, the rest looks good!

2024-12-04 00:19 UTC, lin-yang-ly commented on doc/content/verification_and_validation/ver-1e.md
>  !media comparison_ver-1e.py
Just update it!

2024-12-04 02:11 UTC, simopier requested changes
I'm sorry to keep asking for changes, but given the poor results provided by the analytical solution in the zoomed-in graph, I think we should use a higher time threshold to start the comparison. 

Overall, this is a great improvement to the case!

2024-12-04 02:11 UTC, simopier commented on test/tests/ver-1e/comparison_ver-1e.py
> +ax.set_xlim(0,0.3)
```suggestion
ax.set_xlim(0,0.4)
```

2024-12-04 02:11 UTC, simopier commented on test/tests/ver-1e/comparison_ver-1e.py
> +ax.set_ylim(-0.2,1)
```suggestion
ax.set_ylim(-0.2,1.5)
```

2024-12-04 02:11 UTC, simopier commented on test/tests/ver-1e/comparison_ver-1e.py
> +t0 = 0.01
```suggestion
t0 = 0.2
```

2024-12-04 02:11 UTC, simopier commented on doc/content/verification_and_validation/ver-1e.md
> +       caption=Zoomed-in view of comparison of TMAP8 calculation with the analytical solution for $t$ < 0.3 s. The analytical solution shows unphysical predictions close to $t$ = 0 s, whereas TMAP8's
```suggestion
       caption=Zoomed-in view of comparison of TMAP8 calculation with the analytical solution for $t$ < 0.4 s. The analytical solution shows unphysical predictions close to $t$ = 0 s, whereas TMAP8's predictions are reasonable.
```

2024-12-04 02:11 UTC, simopier commented on doc/content/verification_and_validation/ver-1e.md
> +The error is calculated between the TMAP8 and analytical solution values after $t$ = 0.01 s. This is in order to ignore the unphysical predictions of the analytical solution at very small times as sh
```suggestion
The error is calculated between the TMAP8 and analytical solution values after $t$ = 0.2 s. This is in order to ignore the unphysical predictions of the analytical solution at very small times as shown in [ver-1e_comparison_time_zoomed], which is a close-up view of [ver-1e_comparison_time] close to the start of the simulation. The departure from physical results at low $t$ is due to the limited number of $\lambda_n$ values being used from [eqn:roots]. We use the $\lambda_n$ values from 0 to 100 in this case. The $\lambda_n$ values in larger range will only have limited improvement in the accuracy but increase the running time for the computation of the analytical solutions.
```

2024-12-04 15:43 UTC, lin-yang-ly commented
> I'm sorry to keep asking for changes, but given the poor results provided by the analytical solution in the zoomed-in graph, I think we should use a higher time threshold to start the comparison.
> 
> Overall, this is a great improvement to the case!

Okay, the time threshold of 0.2 make sense to me!

2024-12-04 18:04 UTC, simopier approved these changes
Looks great, thank you @lin-yang-ly!

2024-12-04 18:04 UTC, merged