TMAP8 pore scale example
idaholab/TMAP8 pull request #230
Opened 2024-12-04 22:26 UTC by simopier

(Close. #229)

2024-12-04 22:42 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2582874/), step Sync to remote on 3873d4a wanted to post the following:

View the site [here](https://mooseframework.inl.gov/tmap8/docs/PRs/230/site)

This comment will be updated on new commits.

2024-12-06 15:34 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2587277/), step Generate coverage on 4994139 wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/tmap8/docs/PRs/230/coverage)



This comment will be updated on new commits.

2025-01-17 20:03 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +Although both samples have a density of 80%, they exhibit very different pore interconnectivities, which was demonstrated to affect tritium absorption [!cite](Simon2022).
```suggestion
Although both samples have a density of 80%, they exhibit very different pore interconnectivities, which was demonstrated to affect tritium absorption [!citep](Simon2022).
```

2025-01-17 20:04 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +TMAP8 can import these images using [ImageFunction](ImageFunction.md) and, using a threshold, attribute different contrast values to given phases.
```suggestion
TMAP8 can import these images using the [ImageFunction](ImageFunction.md) object and, using a threshold, attribute different contrast values to given phases.
```

2025-01-17 20:05 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +The simulation time is selected to (1) be large enough to obtain a smooth interface, while (2) staying small enough to prevent significant changes in the microstructure.
```suggestion
The simulation time is selected to be large enough to obtain a smooth interface, while staying small enough to prevent significant changes in the microstructure.
```

2025-01-17 20:06 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +Note that [pore_structure_closed.params](pore_structure_closed.params) and [pore_structure_open.params](pore_structure_open.params) complement the base input file [2D_microstructure_reader_smoothing_
```suggestion
Note that the [pore_structure_closed.params](pore_structure_closed.params) and [pore_structure_open.params](pore_structure_open.params) files complement the base input file [2D_microstructure_reader_smoothing_base.i](2D_microstructure_reader_smoothing_base.i) by providing input and output names.
```

2025-01-17 20:07 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +mpirun -np 4 ~/projects/TMAP8/tmap8-opt -i 2D_microstructure_reader_smoothing_base.i pore_structure_closed.params
Give a brief mention about running this on 4 CPU cores using `mpirun`. Those familiar with running TMAP8 serially might not be as familiar with running it in parallel.

2025-01-17 20:08 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +These pore structures correspond to the ones shown in Fig. 5 in [!cite](Simon2022) and can be found in `~/projects/TMAP8/test/tests/pore_scale_transport/` as `pore_structure_close/pore_structure_clos
```suggestion
These pore structures correspond to the ones shown in Fig. 5 in [!cite](Simon2022) and can be found in `~/projects/TMAP8/test/tests/pore_scale_transport/` as `pore_structure_close/pore_structure_close.e` and `pore_structure_open/pore_structure_open.e` once the simulations are completed. These can be viewed in a visualization software such as [ParaView](https://www.paraview.org/).
```

2025-01-17 20:10 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +where $t$ is time (s), $D_c$ is the diffusion coefficient of tritium in the ceramic material ($\mu$m$^2$/s), $c_t$ is the concentration of trapped tritium (mol/$\mu$m$^{3}$), $K_{gs}$ and $K_{sg}$ ar
```suggestion
where $t$ is time (s), $D_c$ is the diffusion coefficient of tritium in the ceramic material ($\mu$m$^2$/s), $c_t$ is the concentration of trapped tritium (mol/$\mu$m$^{3}$), $K_{gs}$ and $K_{sg}$ are the reaction rates at the surface (mol/$\mu$m$^{3}$/s), and $h_c$ and $h_s$ are dimensionless interpolation functions that delimit the ceramic material and pore surface, respectively (see the next section below).
```

2025-01-17 20:12 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +The equations are encoded into the input file as kernels, which each implement a specific term from the equations
```suggestion
The equations are encoded into the input file as [kernels](Kernels/index.md), which each implement a specific term from the equations
```

2025-01-17 20:14 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +This is commonly used in phase field modeling to describe continuous microstructures.
```suggestion
This is commonly used in [phase field modeling](phase_field/index.md) to describe continuous microstructures.
```

2025-01-17 20:14 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +h_s = 16 \eta^2 (1 - \eta)^2
Why is "16" used here?

2025-01-17 20:15 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +The same numerical methods as described in [!cite](Simon2022) is used here.
```suggestion
The same numerical methods as described in [!cite](Simon2022) are used here.
```

2025-01-17 20:15 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +The numerical methods, including time step, time adaptivity, time integration method, preconditioning, and others are defines in the `Preconditioning` and `Executioner` blocks, as:
```suggestion
The numerical methods, including time step, time adaptivity, time integration method, preconditioning, and others are defined in the `Preconditioning` and `Executioner` blocks, as:
```

2025-01-17 20:17 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +As initial conditions, the ceramic initially contains no tritium, and the pore is filled with $T_2$ with the value from Eq. [eq:BC].
```suggestion
As initial conditions, the ceramic initially contains no tritium, and the pore is filled with $T_2$ with the value from [eq:BC].
```

2025-01-17 20:20 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +Note that these simulations are not run to generate  Fig. 6 from [!cite](Simon2022) on the fly in the documentation like it is custom to do in other [examples](examples/tmap_index.md) and [V&V](verif
While acknowledging that these aren't run on-the-fly, do you think its still useful to show the results to the interested reader?

2025-01-17 20:20 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +Note that these simulations are not run to generate  Fig. 6 from [!cite](Simon2022) on the fly in the documentation like it is custom to do in other [examples](examples/tmap_index.md) and [V&V](verif
```suggestion
Note that these simulations are not run to generate  Fig. 6 from [!cite](Simon2022) on-the-fly in the documentation like it is custom to do in other [examples](examples/tmap_index.md) and [V&V](verification_and_validation/index.md) cases due to the significant time these simulations can take when using a fine mesh. However, using the instructions and details provided above, users can replicate the results presented in [!cite](Simon2022). If any challenge arise or if you have a question while working through this example case, feel free to reach out to the TMAP8 development team on the [TMAP8 GitHub discussion page](https://github.com/idaholab/TMAP8/discussions).
```

2025-01-17 20:21 UTC, cticenhour commented on test/tests/pore_scale_transport/2D_absorption_base.i
> +# Physics:             tritium trapping and detrapping, surface reactions, diffusion.
```suggestion
# Physics:             tritium trapping and detrapping, surface reactions, diffusion
```

2025-01-17 20:23 UTC, cticenhour commented on test/tests/pore_scale_transport/2D_absorption_base.i
> +    expression = '${scale_time}*${scale_quantity}/${scale_length}^3*${reactionRateSurface_sXYg_ref_0}*hsurfaceAD'#-1e-5'#-1e-6'
```suggestion
    expression = '${scale_time}*${scale_quantity}/${scale_length}^3*${reactionRateSurface_sXYg_ref_0}*hsurfaceAD'
```

2025-01-17 20:23 UTC, cticenhour commented on test/tests/pore_scale_transport/2D_absorption_base.i
> +    expression = '${scale_time}*${reactionRateSurface_gXYs_ref_0}*hsurfaceAD*(1-theta)^2'#-1e-5'#-1e-6'
```suggestion
    expression = '${scale_time}*${reactionRateSurface_gXYs_ref_0}*hsurfaceAD*(1-theta)^2'
```

2025-01-18 01:51 UTC, simopier commented on doc/content/examples/pore_scale_transport/index.md
> +h_s = 16 \eta^2 (1 - \eta)^2
I added:

```
Note that the factor 16 ensures that at the middle of the interface, $h_s(\eta = 0.5) = 1$, as desired.
```

2025-01-18 01:58 UTC, simopier commented on test/tests/pore_scale_transport/2D_microstructure_reader_smoothing_base.i
> +num_nodes_y = ${fparse 2*120} # (-)
Yes. 
Good catch! I provided the units for the grain growth parameters.

2025-01-18 02:02 UTC, simopier commented on test/tests/pore_scale_transport/2D_microstructure_reader_smoothing_base.i
> +    compute_halo_maps = true # For displaying HALO fields
The halo is the area of a grain plus an extra area around the grain. It is used by the grain tracker capability to avoid having neighboring grains with similar order parameters: https://mooseframework.inl.gov/source/postprocessors/GrainTracker.html

I don't want to provide too much description in here since this is a complex concept, but this is not an acronym so I'll fix this.

2025-01-18 02:07 UTC, simopier commented on doc/content/examples/pore_scale_transport/index.md
> +Note that these simulations are not run to generate  Fig. 6 from [!cite](Simon2022) on the fly in the documentation like it is custom to do in other [examples](examples/tmap_index.md) and [V&V](verif
In general, adding results that are not generated on the fly can be a maintenance challenge if input files/models are updated without the documentation being updated.

In this case, I prefer to refer to the results of the paper and to the first figure, which shows the results on the right. However, I don't think we need to reproduce the figure here again.

2025-01-22 21:27 UTC, cticenhour requested changes
I found a couple more items to fixup, but then I think we're good.

2025-01-22 21:27 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +To run the input file to reproduce the microstructures shown in Fig. 5 in [!cite](Simon2022), users need to first [install TMAP8](installation.md). Then, to generate the microstructure with closed po
```suggestion
To run the input file to reproduce the microstructures shown in Fig. 5 in [!cite](Simon2022), users need to first [install TMAP8](installation.md). Then, to generate the microstructure with closed pores using 4 CPU cores in parallel with `mpirun`, run:
```

2025-01-22 21:27 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +and to generate the microstructure with open pores using 4 GPU cores in parallel with `mpirun`, run:
```suggestion
and to generate the microstructure with open pores using 4 CPU cores in parallel with `mpirun`, run:
```

2025-01-22 21:27 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +to describe the interface between the ceramic material and the pore
```suggestion
to describe the interface between the ceramic material and the pore.
```

2025-01-22 21:27 UTC, cticenhour commented on doc/content/examples/pore_scale_transport/index.md
> +Note that these simulations are not run to generate  Fig. 6 from [!cite](Simon2022) on the fly in the documentation like it is custom to do in other [examples](examples/tmap_index.md) and [V&V](verif
That's fine - I was just wanting to probe your reasoning a bit. I am fine with leaving it out.

2025-01-22 23:05 UTC, cticenhour approved these changes

2025-01-22 23:36 UTC, merged