Add PhysicalConstant namespace to use consistent values
idaholab/TMAP8 pull request #55
Opened 2023-03-15 23:23 UTC by simopier

- Create PhysicalConstants namespace
- Update existing classes to use PhysicalConstants.h
    
(Close #54)

2023-03-15 23:25 UTC, cticenhour commented
Oops, I think you might have based this off main - lots of merge commits!

2023-03-15 23:28 UTC, simopier commented
> Oops, I think you might have based this off main - lots of merge commits!

Yes, I was like: OMG what did I do again ?!?!? I'm working on fixing it to remove all these commits. Sorry!

2023-03-15 23:34 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1407327/) on 25d38e5 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/tmap8/docs/PRs/55/site)

This comment will be updated on new commits.

2023-03-15 23:35 UTC, simopier commented
That should be better @cticenhour. 😮‍💨

2023-03-16 03:01 UTC, cticenhour requested changes
I like this idea! Did something similar for the EM module, and it helped keep things consistent. A few units typos I noticed.

2023-03-16 03:01 UTC, cticenhour commented on include/utils/PhysicalConstants.h
> +// Avogadro's number (at/mol)
```suggestion
// Avogadro's number (atoms/mol)
```
Prefer to type `at` out for this one

2023-03-16 14:54 UTC, cticenhour approved these changes

2023-03-16 14:54 UTC, merged